#GUI for the project.


from sklearn.externals import joblib
from Tkinter import *

root=Tk()

clf = joblib.load('clf_o.pkl')

def submit_data():
    #global es1
    variable1 = es1.get()
    variable2 = es2.get()
    variable3 = es3.get()
    variable4 = es4.get()
    variable5 = es5.get()
    #variable6 = es6.get()
    variable7 = es7.get()
    variable8 = es8.get()
    variable9 = es9.get()
    variable10 = es10.get()
    variable11 = es12.get()
    variable12 = es12.get()
    variable13 = es13.get()
    variable14 = es14.get()
    variable15 = es15.get()
    variable16 = es16.get()
    variable17 = es17.get()
    variable18 = es18.get()
    variable19 = es19.get()
    variable20 = es20.get()
    variable21 = es21.get()
    variable22 = es22.get()
    variable23 = es23.get()
    variable24 = es24.get()
    print('Clicked')
    print(variable7)
    print(type(variable7))
    prediction=clf.predict([variable1,variable2,variable3,variable4,variable5,variable7,variable8,variable9,variable10,variable11,variable12,variable13,variable14,variable15,variable16,variable17,variable18,variable19,variable20,variable21,variable22,variable23,variable24])
    print(prediction)

    if prediction == 0:
        toplevel = Toplevel()
        msg = Message(toplevel, text='Safe Customer',width=50)
        msg.pack()
        #label_valid=Label(toplevel,text='Potential Defaulter')
    if prediction == 1:
        toplevel = Toplevel()
        msg = Message(toplevel, text='Potential Defaulter',width=50)
        msg.pack()
        #label_valid = Label(toplevel, text=)

#global es1
label1=Label(root,text="CREDIT_Limit")
label1.grid(row=0,column=0)
label2=Label(root,text="SEX")
label2.grid(row=1,column=0)

label3=Label(root,text="Edu")
label3.grid(row=2,column=0)
label4=Label(root,text="Marriage")
label4.grid(row=3,column=0)

label5=Label(root,text="Age")
label5.grid(row=4,column=0)
#label6=Label(root,text="Pay0")
#label6.grid(row=5,column=0)

label7=Label(root,text="History : September")
label7.grid(row=6,column=0)
label8=Label(root,text="History : August")
label8.grid(row=7,column=0)

label9=Label(root,text="History : July")
label9.grid(row=8,column=0)
label10=Label(root,text="History : June")
label10.grid(row=9,column=0)

label11=Label(root,text="History : May")
label11.grid(row=10,column=0)
label12=Label(root,text="History : April")
label12.grid(row=11,column=0)

label13=Label(root,text="Billed : September")
label13.grid(row=12,column=0)
label14=Label(root,text="Billed : August")
label14.grid(row=13,column=0)

label15=Label(root,text="Billed : July")
label15.grid(row=14,column=0)
label16=Label(root,text="Billed : June")
label16.grid(row=15,column=0)

label17=Label(root,text="Billed : May")
label17.grid(row=16,column=0)
label18=Label(root,text="Billed : April")
label18.grid(row=17,column=0)

label19=Label(root,text="Paid : September")
label19.grid(row=18,column=0)
label20=Label(root,text="Paid : August")
label20.grid(row=19,column=0)

label21=Label(root,text="Paid : July")
label21.grid(row=20,column=0)
label22=Label(root,text="Paid : June")
label22.grid(row=21,column=0)

label23=Label(root,text="Paid : May")
label23.grid(row=22,column=0)
label24=Label(root,text="Paid : April")
label24.grid(row=23,column=0)

es1=Entry(root)
es1.grid(row=0,column=1)
es2=Entry(root)
es2.grid(row=1,column=1)
es3=Entry(root)
es3.grid(row=2,column=1)
es4=Entry(root)
es4.grid(row=3,column=1)
es5=Entry(root)
es5.grid(row=4,column=1)
#es6=Entry(root)
#es6.grid(row=5,column=1)
es7=Entry(root)
es7.grid(row=6,column=1)
es8=Entry(root)
es8.grid(row=7,column=1)
es9=Entry(root)
es9.grid(row=8,column=1)
es10=Entry(root)
es10.grid(row=9,column=1)
es11=Entry(root)
es11.grid(row=10,column=1)
es12=Entry(root)
es12.grid(row=11,column=1)
es13=Entry(root)
es13.grid(row=12,column=1)
es14=Entry(root)
es14.grid(row=13,column=1)
es15=Entry(root)
es15.grid(row=14,column=1)
es16=Entry(root)
es16.grid(row=15,column=1)
es17=Entry(root)
es17.grid(row=16,column=1)
es18=Entry(root)
es18.grid(row=17,column=1)
es19=Entry(root)
es19.grid(row=18,column=1)
es20=Entry(root)
es20.grid(row=19,column=1)
es21=Entry(root)
es21.grid(row=20,column=1)
es22=Entry(root)
es22.grid(row=21,column=1)
es23=Entry(root)
es23.grid(row=22,column=1)
es24=Entry(root)
es24.grid(row=23,column=1)
#submit = Tkinter.Button(root,text='Enter',command=submit_data)
#submit.grid

thebutton= Button(root,text="Submit",fg="Blue",command=submit_data)
thebutton.grid(row=24,column=1)

#variable1=es23.get()
#print(variable1)
labelc1=Label(root,text="Amount in Units")
labelc1.grid(row=0,column=2)
labelc2=Label(root,text="1=Male,2=Female")
labelc2.grid(row=1,column=2)
labelc3=Label(root,text="1 = graduate school; 2 = university; 3 = high school; 4 = others")
labelc3.grid(row=2,column=2)
labelc4=Label(root,text="1 = married; 2 = single; 3 = others")
labelc4.grid(row=3,column=2)
labelc5=Label(root,text="Years")
labelc5.grid(row=4,column=2)
labelc6=Label(root,text=" **Past History** -1 = pay duly; else N = payment delay for N month")
labelc6.grid(row=6,column=2)
labelc7=Label(root,text=" **Amount of bill statement**")
labelc7.grid(row=12,column=2)
labelc8=Label(root,text="**Amount of previous payments**")
labelc8.grid(row=18,column=2)


root.mainloop()
"""
top = Tk()
L1 = Label(top, text="CREDIT_BALANCE")
L1.pack( side = LEFT)
E1 = Entry(top, bd =5)
E1.grid(row=0)

L2 = Label(top, text="SEX")
L2.pack( side = LEFT)
E2 = Entry(top, bd =5)
E2.pack(side = RIGHT)
E1.grid(row=1)

L3 = Label(top, text="EDU")
L3.pack( side = LEFT)
E3 = Entry(top, bd =5)
E3.pack(side = RIGHT)

L4 = Label(top, text="MARRIAGE")
L4.pack( side = LEFT)
E4 = Entry(top, bd =5)
E4.pack(side = RIGHT)

L5 = Label(top, text="AGE")
L5.pack( side = LEFT)
E5 = Entry(top, bd =5)
E5.pack(side = RIGHT)

L6 = Label(top, text="PAY0")
L6.pack( side = LEFT)
E6 = Entry(top, bd =5)
E6.pack(side = RIGHT)

L7 = Label(top, text="PAY2")
L7.pack( side = LEFT)
E7 = Entry(top, bd =5)
E7.pack(side = RIGHT)

L8 = Label(top, text="PAY3")
L8.pack( side = LEFT)
E8 = Entry(top, bd =5)
E8.pack(side = RIGHT)

L9 = Label(top, text="PAY4")
L9.pack( side = LEFT)
E9 = Entry(top, bd =5)
E9.pack(side = RIGHT)

L10 = Label(top, text="PAY5")
L10.pack( side = LEFT)
E10 = Entry(top, bd =5)
E10.pack(side = RIGHT)

L11 = Label(top, text="PAY6")
L11.pack( side = LEFT)
E11 = Entry(top, bd =5)
E11.pack(side = RIGHT)

L12 = Label(top, text="BILL_AMT1")
L12.pack( side = LEFT)
E12 = Entry(top, bd =5)
E12.pack(side = RIGHT)

L13 = Label(top, text="BILL_AMT2")
L13.pack( side = LEFT)
E13 = Entry(top, bd =5)
E13.pack(side = RIGHT)

L14 = Label(top, text="BILL_AMT3")
L14.pack( side = LEFT)
E14 = Entry(top, bd =5)
E14.pack(side = RIGHT)

L15 = Label(top, text="BILL_AMT4")
L15.pack( side = LEFT)
E15 = Entry(top, bd =5)
E15.pack(side = RIGHT)

L15 = Label(top, text="BILL_AMT5")
L15.pack( side = LEFT)
E15 = Entry(top, bd =5)
E15.pack(side = RIGHT)

L15 = Label(top, text="BILL_AMT6")
L15.pack( side = LEFT)
E15 = Entry(top, bd =5)
E15.pack(side = RIGHT)

L12 = Label(top, text="PAY_AMT1")
L12.pack( side = LEFT)
E12 = Entry(top, bd =5)
E12.pack(side = RIGHT)

L13 = Label(top, text="PAY_AMT2")
L13.pack( side = LEFT)
E13 = Entry(top, bd =5)
E13.pack(side = RIGHT)

L14 = Label(top, text="PAY_AMT3")
L14.pack( side = LEFT)
E14 = Entry(top, bd =5)
E14.pack(side = RIGHT)

L15 = Label(top, text="PAY_AMT4")
L15.pack( side = LEFT)
E15 = Entry(top, bd =5)
E15.pack(side = RIGHT)

L15 = Label(top, text="PAY_AMT5")
L15.pack( side = LEFT)
E15 = Entry(top, bd =5)
E15.pack(side = RIGHT)

L15 = Label(top, text="PAY_AMT6")
L15.pack( side = LEFT)
E15 = Entry(top, bd =5)
E15.pack(side = RIGHT)

clf = joblib.load('clf_o.pkl')

top.mainloop()

"""